pcm::PCManager Class Reference
#include <PCManager.h>
Public Member Functions
PCManager ()
PCManager (bool visualizationFlag)
virtual ~PCManager ()
vector< PCLCloudPtr > getCloudFromIdx (PrimitiveIdxPtr indices)
void visualize ()
PCPrimitivePtr getPrimitiveShape (int idx)
int addPrimitiveShape (string shapeName, PCLCloudPtr cloud, PCLNormalPtr norms, bool visFlag)
int clearPtimitiveShape ()
PCLCloudPtr getOriginalCloud ()
PointCloud2 getOriginalCloudRosMsg ()
PCLNormalPtr getOriginalNormal ()
PointCloud2 getOriginalNormalRosMsg ()
bool getVisualizationFlag ()
PCLVisualizer getVisor ()
void setOriginalCloud (PCLCloudPtr cloud)
void setOriginalCloud (PCLCloudPtr cloud, int normSearch, float downSpanX, float downSpanY, float downSpanZ)
void setOriginalCloud (PointCloud2Ptr cloud)
void setOriginalCloud (PointCloud2Ptr cloud, int normSearch, float downSpanX, float downSpanY, float downSpanZ)
void setVisualizationFlag (bool flag)
Static Public Member Functions
static PCLCloudPtr copyCloud (PCLCloudPtr input)
static PCLNormalPtr copyNormals (PCLNormalPtr input)
static ModelCoefficients::Ptr copyCoefficients (ModelCoefficients::Ptr input)
static PCLCloudPtr downSampling (PCLCloudPtr input)
static PCLCloudPtr downSampling (PCLCloudPtr input, float span)
static PCLCloudPtr downSampling (PCLCloudPtr input, float spanX, float spanY, float spanZ)
static PCLNormalPtr estimateNormal (PCLCloudPtr input)
static PCLNormalPtr estimateNormal (PCLCloudPtr input, int search)
static PointCloud2 cloudToRosMsg (PCLCloudPtr input)
static PCLCloudPtr cloudForRosMsg (PointCloud2 input)
static PCLCloudPtr cloudForRosMsg (PointCloud2Ptr input)
static PointCloud2 normToRosMsg (PCLNormalPtr input)
static PCLNormalPtr normForRosMsg (PointCloud2 input)
static vector< int > inlierToVectorMsg (PointIndices::Ptr inliers)
static vector< float > coefficientToVectorMsg (ModelCoefficients::Ptr coefficients)
static PCLVisualizer createVisor (string title)
static void updateVisor (PCLVisualizer viewer, PCLCloudPtr cloud, int R, int G, int B, string name)
static void updateVisor (PCLVisualizer viewer, PCLCloudPtr cloud, string name)
static void updateVisor (PCLVisualizer viewer, PCLCloudPtr cloud, PCLNormalPtr normals, int R, int G, int B, string name)
static void updateVisor (PCLVisualizer viewer, PCLCloudPtr cloud, PCLNormalPtr normals, string name)
static void updateVisor (PCLVisualizer viewer, PointXYZ point, int R, int G, int B, string name)
static void updateVisor (PCLVisualizer viewer, PointXYZ point, string name)
static void clearVisor (PCLVisualizer viewer)
static vector< PCLCloudPtr > getCloudFromIdx (PCLCloudPtr originalCloud, PrimitiveIdxPtr indices)
static bool writeToFile (string txt, string filePath)
Static Public Attributes
static const bool DEFAULT_VISUALIZATION_FLAG = false
static const int VISUALIZER_POINT_SIZE = 3
static const int VISUALIZER_POINT_SIZE_BIG = 10
static const string DEFAULT_CLOUD_NAME_SUFFIX = `_cloud`
static const string DEFAULT_NORM_NAME_SUFFIX = `_normal`
static const string DEFAULT_ORIGINAL_CLOUD_VIEWER_NAME = `original`
static const int DEFAULT_NORM_LEVEL = 5
static const float DEFAULT_NORM_SCALE = 0.02f
static const string DEFAULT_VISUALIZER_TITLE = `PointCloud manager`
static const int DEFAULT_NORM_SEARCH = 50
static const float DEFAULT_DOWSEAMPLIG_RATE = 0.01f
static const string DEEP_FILTER_SERVICE_NAME = `deepFilterSrv`
static const string SUPPORT_FILTER_SERVICE_NAME = `supportSegmentationSrv`
static const string CUSTER_FILTER_SERVICE_NAME = `clusterSegmentationSrv`
static const string ARM_FILTER_SERVICE_NAME = `robotArmCloudFiltering`
static const string RANSAC_SPHERE_FILTER_SERVICE_NAME = `sphereSegmentationSrv`
static const string RANSAC_CYLINDER_FILTER_SERVICE_NAME = `cylinderSegmentationSrv`
static const string RANSAC_CONE_FILTER_SERVICE_NAME = `coneSegmentationSrv`
static const string RANSAC_PLANE_FILTER_SERVICE_NAME = `planeSegmentationSrv`
static const string SEMANTIC_SCENE_RECOGNITION_SERVICE_NAME = `semanticSceneRecognitonSrv`
static const float DEFAULT_SERVICE_PARAMETER_REQUEST = -1.0f
Private Member Functions
void initialize (bool visualizationFlag)
Private Attributes
PCLCloudPtr originalCloud
PCLNormalPtr originalNorms
PCLVisualizer visor
bool visualizationFlag
vector< PCPrimitivePtr > primitiveList
Detailed Description
Definition at line 31 of file PCManager.h.
Constructor & Destructor Documentation
pcm::PCManager::PCManager ()
Definition at line 239 of file PCManager.cpp.
References DEFAULT_VISUALIZATION_FLAG, and initialize().
pcm::PCManager::PCManager (bool visualizationFlag)
Definition at line 242 of file PCManager.cpp.
References initialize().
pcm::PCManager::~PCManager () [virtual]
Definition at line 247 of file PCManager.cpp.
Member Function Documentation
int pcm::PCManager::addPrimitiveShape (string shapeName, PCLCloudPtr cloud, PCLNormalPtr norms, bool visFlag)
int pcm::PCManager::clearPtimitiveShape ()
void pcm::PCManager::clearVisor (PCLVisualizer viewer) [static]
Definition at line 179 of file PCManager.cpp.
PCLCloudPtr pcm::PCManager::cloudForRosMsg (PointCloud2 input) [static]
Definition at line 101 of file PCManager.cpp.
Referenced by clusterize(), ransacConeDetaction(), ransacCylinderDetaction(), ransacPlaneDetaction(), ransacSphereDetaction(), and setOriginalCloud().
PCLCloudPtr pcm::PCManager::cloudForRosMsg (PointCloud2Ptr input) [static]
Definition at line 96 of file PCManager.cpp.
PointCloud2 pcm::PCManager::cloudToRosMsg (PCLCloudPtr input) [static]
Definition at line 91 of file PCManager.cpp.
Referenced by getOriginalCloudRosMsg().
vector< float > pcm::PCManager::coefficientToVectorMsg (ModelCoefficients::Ptr coefficients) [static]
Definition at line 123 of file PCManager.cpp.
Referenced by ransacConeDetaction(), ransacCylinderDetaction(), ransacPlaneDetaction(), and ransacSphereDetaction().
PCLCloudPtr pcm::PCManager::copyCloud (PCLCloudPtr input) [static]
Definition at line 41 of file PCManager.cpp.
ModelCoefficients::Ptr pcm::PCManager::copyCoefficients (ModelCoefficients::Ptr input) [static]
Definition at line 60 of file PCManager.cpp.
PCLNormalPtr pcm::PCManager::copyNormals (PCLNormalPtr input) [static]
Definition at line 54 of file PCManager.cpp.
PCLVisualizer pcm::PCManager::createVisor (string title) [static]
Definition at line 132 of file PCManager.cpp.
Referenced by initialize(), main(), and setVisualizationFlag().
PCLCloudPtr pcm::PCManager::downSampling (PCLCloudPtr input) [static]
Definition at line 66 of file PCManager.cpp.
References DEFAULT_DOWSEAMPLIG_RATE.
Referenced by downSampling(), and setOriginalCloud().
PCLCloudPtr pcm::PCManager::downSampling (PCLCloudPtr input, float span) [static]
Definition at line 69 of file PCManager.cpp.
References downSampling().
PCLCloudPtr pcm::PCManager::downSampling (PCLCloudPtr input, float spanX, float spanY, float spanZ) [static]
Definition at line 72 of file PCManager.cpp.
References pcm::sor.
PCLNormalPtr pcm::PCManager::estimateNormal (PCLCloudPtr input) [static]
Definition at line 79 of file PCManager.cpp.
References DEFAULT_NORM_SEARCH.
Referenced by setOriginalCloud().
PCLNormalPtr pcm::PCManager::estimateNormal (PCLCloudPtr input, int search) [static]
Definition at line 82 of file PCManager.cpp.
References pcm::ne, and pcm::tree().
vector< PCLCloudPtr > pcm::PCManager::getCloudFromIdx (PCLCloudPtr originalCloud, PrimitiveIdxPtr indices) [static]
Definition at line 185 of file PCManager.cpp.
Referenced by getCloudFromIdx().
vector< PCLCloudPtr > pcm::PCManager::getCloudFromIdx (PrimitiveIdxPtr indices)
Definition at line 231 of file PCManager.cpp.
References getCloudFromIdx(), and originalCloud.
PCLCloudPtr pcm::PCManager::getOriginalCloud ()
Definition at line 285 of file PCManager.cpp.
References originalCloud.
PointCloud2 pcm::PCManager::getOriginalCloudRosMsg ()
Definition at line 288 of file PCManager.cpp.
References cloudToRosMsg(), and originalCloud.
PCLNormalPtr pcm::PCManager::getOriginalNormal ()
Definition at line 292 of file PCManager.cpp.
References originalNorms.
PointCloud2 pcm::PCManager::getOriginalNormalRosMsg ()
Definition at line 295 of file PCManager.cpp.
References normToRosMsg(), and originalNorms.
PCPrimitivePtr pcm::PCManager::getPrimitiveShape (int idx)
PCLVisualizer pcm::PCManager::getVisor ()
Definition at line 302 of file PCManager.cpp.
References visor.
bool pcm::PCManager::getVisualizationFlag ()
Definition at line 299 of file PCManager.cpp.
References visualizationFlag.
void pcm::PCManager::initialize (bool visualizationFlag) [private]
Definition at line 343 of file PCManager.cpp.
References createVisor(), DEFAULT_VISUALIZER_TITLE, visor, and visualizationFlag.
Referenced by PCManager().
vector< int > pcm::PCManager::inlierToVectorMsg (PointIndices::Ptr inliers) [static]
Definition at line 116 of file PCManager.cpp.
Referenced by ransacConeDetaction(), ransacCylinderDetaction(), ransacPlaneDetaction(), and ransacSphereDetaction().
PCLNormalPtr pcm::PCManager::normForRosMsg (PointCloud2 input) [static]
Definition at line 111 of file PCManager.cpp.
Referenced by ransacConeDetaction(), ransacCylinderDetaction(), ransacPlaneDetaction(), and ransacSphereDetaction().
PointCloud2 pcm::PCManager::normToRosMsg (PCLNormalPtr input) [static]
Definition at line 106 of file PCManager.cpp.
Referenced by getOriginalNormalRosMsg().
void pcm::PCManager::setOriginalCloud (PCLCloudPtr cloud)
Definition at line 308 of file PCManager.cpp.
References DEFAULT_DOWSEAMPLIG_RATE, and DEFAULT_NORM_SEARCH.
Referenced by setOriginalCloud().
void pcm::PCManager::setOriginalCloud (PCLCloudPtr cloud, int normSearch, float downSpanX, float downSpanY, float downSpanZ)
Definition at line 311 of file PCManager.cpp.
References downSampling(), estimateNormal(), originalCloud, and originalNorms.
void pcm::PCManager::setOriginalCloud (PointCloud2Ptr cloud)
Definition at line 319 of file PCManager.cpp.
References DEFAULT_DOWSEAMPLIG_RATE, DEFAULT_NORM_SEARCH, and setOriginalCloud().
void pcm::PCManager::setOriginalCloud (PointCloud2Ptr cloud, int normSearch, float downSpanX, float downSpanY, float downSpanZ)
Definition at line 322 of file PCManager.cpp.
References cloudForRosMsg(), and setOriginalCloud().
void pcm::PCManager::setVisualizationFlag (bool flag)
Definition at line 326 of file PCManager.cpp.
References createVisor(), DEFAULT_VISUALIZER_TITLE, visor, and visualizationFlag.
void pcm::PCManager::updateVisor (PCLVisualizer viewer, PCLCloudPtr cloud, int R, int G, int B, string name) [static]
Definition at line 154 of file PCManager.cpp.
References VISUALIZER_POINT_SIZE.
Referenced by ransacConeDetaction(), ransacCylinderDetaction(), and updateVisor().
void pcm::PCManager::updateVisor (PCLVisualizer viewer, PCLCloudPtr cloud, string name) [static]
Definition at line 162 of file PCManager.cpp.
References updateVisor().
void pcm::PCManager::updateVisor (PCLVisualizer viewer, PCLCloudPtr cloud, PCLNormalPtr normals, int R, int G, int B, string name) [static]
Definition at line 166 of file PCManager.cpp.
References DEFAULT_NORM_LEVEL, DEFAULT_NORM_NAME_SUFFIX, DEFAULT_NORM_SCALE, and VISUALIZER_POINT_SIZE.
void pcm::PCManager::updateVisor (PCLVisualizer viewer, PCLCloudPtr cloud, PCLNormalPtr normals, string name) [static]
Definition at line 176 of file PCManager.cpp.
References updateVisor().
void pcm::PCManager::updateVisor (PCLVisualizer viewer, PointXYZ point, int R, int G, int B, string name) [static]
Definition at line 140 of file PCManager.cpp.
References VISUALIZER_POINT_SIZE_BIG.
void pcm::PCManager::updateVisor (PCLVisualizer viewer, PointXYZ point, string name) [static]
Definition at line 150 of file PCManager.cpp.
References updateVisor().
void pcm::PCManager::visualize ()
bool pcm::PCManager::writeToFile (string txt, string filePath) [static]
Definition at line 219 of file PCManager.cpp.
Member Data Documentation
const string pcm::PCManager::ARM_FILTER_SERVICE_NAME = `robotArmCloudFiltering` [static]
Definition at line 127 of file PCManager.h.
const string pcm::PCManager::CUSTER_FILTER_SERVICE_NAME = `clusterSegmentationSrv` [static]
Definition at line 126 of file PCManager.h.
const string pcm::PCManager::DEEP_FILTER_SERVICE_NAME = `deepFilterSrv` [static]
Definition at line 124 of file PCManager.h.
const string pcm::PCManager::DEFAULT_CLOUD_NAME_SUFFIX = `_cloud` [static]
Definition at line 114 of file PCManager.h.
const float pcm::PCManager::DEFAULT_DOWSEAMPLIG_RATE = 0.01f [static]
Definition at line 122 of file PCManager.h.
Referenced by downSampling(), and setOriginalCloud().
const int pcm::PCManager::DEFAULT_NORM_LEVEL = 5 [static]
Definition at line 117 of file PCManager.h.
Referenced by updateVisor().
const string pcm::PCManager::DEFAULT_NORM_NAME_SUFFIX = `_normal` [static]
Definition at line 115 of file PCManager.h.
Referenced by updateVisor().
const float pcm::PCManager::DEFAULT_NORM_SCALE = 0.02f [static]
Definition at line 118 of file PCManager.h.
Referenced by updateVisor().
const int pcm::PCManager::DEFAULT_NORM_SEARCH = 50 [static]
Definition at line 121 of file PCManager.h.
Referenced by estimateNormal(), and setOriginalCloud().
const string pcm::PCManager::DEFAULT_ORIGINAL_CLOUD_VIEWER_NAME = `original` [static]
Definition at line 116 of file PCManager.h.
const float pcm::PCManager::DEFAULT_SERVICE_PARAMETER_REQUEST = -1.0f [static]
Definition at line 134 of file PCManager.h.
const bool pcm::PCManager::DEFAULT_VISUALIZATION_FLAG = false [static]
Definition at line 111 of file PCManager.h.
Referenced by PCManager().
const string pcm::PCManager::DEFAULT_VISUALIZER_TITLE = `PointCloud manager` [static]
Definition at line 119 of file PCManager.h.
Referenced by initialize(), and setVisualizationFlag().
PCLCloudPtr pcm::PCManager::originalCloud [private]
Definition at line 33 of file PCManager.h.
Referenced by getCloudFromIdx(), getOriginalCloud(), getOriginalCloudRosMsg(), and setOriginalCloud().
PCLNormalPtr pcm::PCManager::originalNorms [private]
Definition at line 34 of file PCManager.h.
Referenced by getOriginalNormal(), getOriginalNormalRosMsg(), and setOriginalCloud().
vector< PCPrimitivePtr> pcm::PCManager::primitiveList [private]
Definition at line 39 of file PCManager.h.
const string pcm::PCManager::RANSAC_CONE_FILTER_SERVICE_NAME = `coneSegmentationSrv` [static]
Definition at line 130 of file PCManager.h.
Referenced by main().
const string pcm::PCManager::RANSAC_CYLINDER_FILTER_SERVICE_NAME = `cylinderSegmentationSrv` [static]
Definition at line 129 of file PCManager.h.
Referenced by main().
const string pcm::PCManager::RANSAC_PLANE_FILTER_SERVICE_NAME = `planeSegmentationSrv` [static]
Definition at line 131 of file PCManager.h.
Referenced by main().
const string pcm::PCManager::RANSAC_SPHERE_FILTER_SERVICE_NAME = `sphereSegmentationSrv` [static]
Definition at line 128 of file PCManager.h.
Referenced by main().
const string pcm::PCManager::SEMANTIC_SCENE_RECOGNITION_SERVICE_NAME = `semanticSceneRecognitonSrv` [static]
Definition at line 132 of file PCManager.h.
const string pcm::PCManager::SUPPORT_FILTER_SERVICE_NAME = `supportSegmentationSrv` [static]
Definition at line 125 of file PCManager.h.
PCLVisualizer pcm::PCManager::visor [private]
Definition at line 36 of file PCManager.h.
Referenced by getVisor(), initialize(), and setVisualizationFlag().
bool pcm::PCManager::visualizationFlag [private]
Definition at line 37 of file PCManager.h.
Referenced by getVisualizationFlag(), initialize(), and setVisualizationFlag().
const int pcm::PCManager::VISUALIZER_POINT_SIZE = 3 [static]
Definition at line 112 of file PCManager.h.
Referenced by updateVisor().
const int pcm::PCManager::VISUALIZER_POINT_SIZE_BIG = 10 [static]
Definition at line 113 of file PCManager.h.
Referenced by updateVisor().
The documentation for this class was generated from the following files:
PCManager.h
PCManager.cpp