clusterSegmentationServer.cpp File Reference
#include `ros/ros.h`
*
#include <iostream>
*
#include `pitt_msgs/ClusterSegmentation.h`
*
#include `pitt_msgs/InliersCluster.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl/segmentation/extract_clusters.h>
*
#include <std_msgs/String.h>
*
#include <pcl_conversions/pcl_conversions.h>
*
#include `../PCStaticProcessing/PCManager.h`
*
Functions
bool clusterize (ClusterSegmentation::Request &req, ClusterSegmentation::Response &res)
int main (int argc, char **argv)
Variables
const float TOLLERANCE_DEFAULT = 0.03f
const float MIN_CLUSTER_RATE_DEFAULT = 0.01f
const float MAX_CLUSTER_RATE_DEFAULT = 0.99f
const float MIN_INPUT_SIZE_DEFAULT = 30.0f
Function Documentation
bool clusterize (ClusterSegmentation::Request & req, ClusterSegmentation::Response & res)
Definition at line 33 of file clusterSegmentationServer.cpp.
References pcm::PCManager::cloudForRosMsg(), MAX_CLUSTER_RATE_DEFAULT, MIN_CLUSTER_RATE_DEFAULT, MIN_INPUT_SIZE_DEFAULT, TOLLERANCE_DEFAULT, and pcm::tree().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 118 of file clusterSegmentationServer.cpp.
References clusterize().
Variable Documentation
const float MAX_CLUSTER_RATE_DEFAULT = 0.99f
Definition at line 29 of file clusterSegmentationServer.cpp.
Referenced by clusterize().
const float MIN_CLUSTER_RATE_DEFAULT = 0.01f
Definition at line 28 of file clusterSegmentationServer.cpp.
Referenced by clusterize().
const float MIN_INPUT_SIZE_DEFAULT = 30.0f
Definition at line 30 of file clusterSegmentationServer.cpp.
Referenced by clusterize().
const float TOLLERANCE_DEFAULT = 0.03f
Definition at line 27 of file clusterSegmentationServer.cpp.
Referenced by clusterize().