coneSegmentationServer.cpp File Reference
#include `ros/ros.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl/segmentation/sac_segmentation.h>
*
#include `../PCStaticProcessing/PCManager.h`
*
#include `pitt_msgs/PrimitiveSegmentation.h`
*
Classes
struct vector3d
Functions
vector3d getNormalizeAxesDirectionVector (ModelCoefficients::Ptr coefficients)
vector3d getPointOnAxes (ModelCoefficients::Ptr coefficients, vector3d direction, float t)
vector3d getVectorBetweenPoints (vector3d p1, vector3d p2)
bool ransacConeDetaction (PrimitiveSegmentation::Request &req, PrimitiveSegmentation::Response &res)
int main (int argc, char **argv)
Variables
const float NORMAL_DISTANCE_WEIGHT_DEFAULT = 0.0006f
const float DISTANCE_THRESHOLD_DEFAULT = 0.0055f
const int MAX_ITERATION_DEFAULT = 1000
const float MIN_RADIUS_LIMIT = 0.001
const float MAX_RADIUS_LIMIT = 0.500
const float EPS_ANGLE = 0.4f
const float MIN_OPENING_ANGLE = 10.0f
const float MAX_OPENING_ANGLE = 170.0f
const bool VISUALIZE_RESULT = false
boost::shared_ptr
*
< visualization::PCLVisualizer > vis
Function Documentation
vector3d getNormalizeAxesDirectionVector (ModelCoefficients::Ptr coefficients)
Definition at line 36 of file coneSegmentationServer.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacConeDetaction().
vector3d getPointOnAxes (ModelCoefficients::Ptr coefficients, vector3d direction, float t)
Definition at line 47 of file coneSegmentationServer.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacConeDetaction().
vector3d getVectorBetweenPoints (vector3d p1, vector3d p2)
Definition at line 56 of file coneSegmentationServer.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacConeDetaction().
int main (int argc, char ** argv)
Definition at line 217 of file coneSegmentationServer.cpp.
References pcm::PCManager::createVisor(), pcm::PCManager::RANSAC_CONE_FILTER_SERVICE_NAME, ransacConeDetaction(), vis, and VISUALIZE_RESULT.
bool ransacConeDetaction (PrimitiveSegmentation::Request & req, PrimitiveSegmentation::Response & res)
Definition at line 65 of file coneSegmentationServer.cpp.
References pcm::PCManager::cloudForRosMsg(), pcm::PCManager::coefficientToVectorMsg(), DISTANCE_THRESHOLD_DEFAULT, EPS_ANGLE, getNormalizeAxesDirectionVector(), getPointOnAxes(), getVectorBetweenPoints(), pcm::PCManager::inlierToVectorMsg(), MAX_ITERATION_DEFAULT, MAX_OPENING_ANGLE, MAX_RADIUS_LIMIT, MIN_OPENING_ANGLE, MIN_RADIUS_LIMIT, NORMAL_DISTANCE_WEIGHT_DEFAULT, pcm::PCManager::normForRosMsg(), seg, pcm::PCManager::updateVisor(), vis, VISUALIZE_RESULT, vector3d::x, vector3d::y, and vector3d::z.
Referenced by main().
Variable Documentation
const float DISTANCE_THRESHOLD_DEFAULT = 0.0055f
Definition at line 16 of file coneSegmentationServer.cpp.
Referenced by ransacConeDetaction().
const float EPS_ANGLE = 0.4f
Definition at line 20 of file coneSegmentationServer.cpp.
Referenced by ransacConeDetaction().
const int MAX_ITERATION_DEFAULT = 1000
Definition at line 17 of file coneSegmentationServer.cpp.
Referenced by ransacConeDetaction().
const float MAX_OPENING_ANGLE = 170.0f
Definition at line 22 of file coneSegmentationServer.cpp.
Referenced by ransacConeDetaction().
const float MAX_RADIUS_LIMIT = 0.500
Definition at line 19 of file coneSegmentationServer.cpp.
Referenced by ransacConeDetaction().
const float MIN_OPENING_ANGLE = 10.0f
Definition at line 21 of file coneSegmentationServer.cpp.
Referenced by ransacConeDetaction().
const float MIN_RADIUS_LIMIT = 0.001
Definition at line 18 of file coneSegmentationServer.cpp.
Referenced by ransacConeDetaction().
const float NORMAL_DISTANCE_WEIGHT_DEFAULT = 0.0006f
Definition at line 15 of file coneSegmentationServer.cpp.
Referenced by ransacConeDetaction().
boost::shared_ptr< visualization::PCLVisualizer> vis
Definition at line 33 of file coneSegmentationServer.cpp.
Referenced by main(), and ransacConeDetaction().
const bool VISUALIZE_RESULT = false
Definition at line 32 of file coneSegmentationServer.cpp.
Referenced by main(), and ransacConeDetaction().