cylinderSegmentationServer.cpp File Reference
#include `ros/ros.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl/segmentation/sac_segmentation.h>
*
#include `../PCStaticProcessing/PCManager.h`
*
#include `pitt_msgs/PrimitiveSegmentation.h`
*
Classes
struct vector3d
Functions
vector3d getNormalizeAxesDirectionVector (ModelCoefficients::Ptr coefficients)
vector3d getPointOnAxes (ModelCoefficients::Ptr coefficients, vector3d direction, float t)
vector3d getVectorBetweenPoints (vector3d p1, vector3d p2)
bool ransacCylinderDetaction (PrimitiveSegmentation::Request &req, PrimitiveSegmentation::Response &res)
int main (int argc, char **argv)
Variables
const float NORMAL_DISTANCE_WEIGHT_DEFAULT = 0.001f
const float DISTANCE_THRESHOLD_DEFAULT = 0.008f
const int MAX_ITERATION_DEFAULT = 1000
const float MIN_RADIUS_LIMIT = 0.005
const float MAX_RADIUS_LIMIT = 0.500
const float EPS_ANGLE = 0.0001f
const float MIN_OPENING_ANGLE = 50.0f
const float MAX_OPENING_ANGLE = 180.0f
const bool VISUALIZE_RESULT = false
boost::shared_ptr
*
< visualization::PCLVisualizer > vis
Function Documentation
vector3d getNormalizeAxesDirectionVector (ModelCoefficients::Ptr coefficients)
Definition at line 37 of file cylinderSegmentationServer.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacCylinderDetaction().
vector3d getPointOnAxes (ModelCoefficients::Ptr coefficients, vector3d direction, float t)
Definition at line 48 of file cylinderSegmentationServer.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacCylinderDetaction().
vector3d getVectorBetweenPoints (vector3d p1, vector3d p2)
Definition at line 57 of file cylinderSegmentationServer.cpp.
References vector3d::x, vector3d::y, and vector3d::z.
Referenced by ransacCylinderDetaction().
int main (int argc, char ** argv)
Definition at line 220 of file cylinderSegmentationServer.cpp.
References pcm::PCManager::createVisor(), pcm::PCManager::RANSAC_CYLINDER_FILTER_SERVICE_NAME, ransacCylinderDetaction(), vis, and VISUALIZE_RESULT.
bool ransacCylinderDetaction (PrimitiveSegmentation::Request & req, PrimitiveSegmentation::Response & res)
Definition at line 66 of file cylinderSegmentationServer.cpp.
References pcm::PCManager::cloudForRosMsg(), pcm::PCManager::coefficientToVectorMsg(), DISTANCE_THRESHOLD_DEFAULT, EPS_ANGLE, getNormalizeAxesDirectionVector(), getPointOnAxes(), getVectorBetweenPoints(), pcm::PCManager::inlierToVectorMsg(), MAX_ITERATION_DEFAULT, MAX_OPENING_ANGLE, MAX_RADIUS_LIMIT, MIN_OPENING_ANGLE, MIN_RADIUS_LIMIT, NORMAL_DISTANCE_WEIGHT_DEFAULT, pcm::PCManager::normForRosMsg(), seg, pcm::PCManager::updateVisor(), vis, VISUALIZE_RESULT, vector3d::x, vector3d::y, and vector3d::z.
Referenced by main().
Variable Documentation
const float DISTANCE_THRESHOLD_DEFAULT = 0.008f
Definition at line 17 of file cylinderSegmentationServer.cpp.
Referenced by ransacCylinderDetaction().
const float EPS_ANGLE = 0.0001f
Definition at line 21 of file cylinderSegmentationServer.cpp.
Referenced by ransacCylinderDetaction().
const int MAX_ITERATION_DEFAULT = 1000
Definition at line 18 of file cylinderSegmentationServer.cpp.
Referenced by ransacCylinderDetaction().
const float MAX_OPENING_ANGLE = 180.0f
Definition at line 23 of file cylinderSegmentationServer.cpp.
Referenced by ransacCylinderDetaction().
const float MAX_RADIUS_LIMIT = 0.500
Definition at line 20 of file cylinderSegmentationServer.cpp.
Referenced by ransacCylinderDetaction().
const float MIN_OPENING_ANGLE = 50.0f
Definition at line 22 of file cylinderSegmentationServer.cpp.
Referenced by ransacCylinderDetaction().
const float MIN_RADIUS_LIMIT = 0.005
Definition at line 19 of file cylinderSegmentationServer.cpp.
Referenced by ransacCylinderDetaction().
const float NORMAL_DISTANCE_WEIGHT_DEFAULT = 0.001f
Definition at line 16 of file cylinderSegmentationServer.cpp.
Referenced by ransacCylinderDetaction().
boost::shared_ptr< visualization::PCLVisualizer> vis
Definition at line 34 of file cylinderSegmentationServer.cpp.
Referenced by main(), and ransacCylinderDetaction().
const bool VISUALIZE_RESULT = false
Definition at line 33 of file cylinderSegmentationServer.cpp.
Referenced by main(), and ransacCylinderDetaction().