sphereSegmentationServer.cpp File Reference
#include `ros/ros.h`
*
#include <pcl_ros/point_cloud.h>
*
#include <pcl/segmentation/sac_segmentation.h>
*
#include `../PCStaticProcessing/PCManager.h`
*
#include `pitt_msgs/PrimitiveSegmentation.h`
*
Functions
bool ransacSphereDetaction (PrimitiveSegmentation::Request &req, PrimitiveSegmentation::Response &res)
int main (int argc, char **argv)
Variables
const float NORMAL_DISTANCE_WEIGHT_DEFAULT = 0.001f
const float DISTANCE_THRESHOLD_DEFAULT = 0.007f
const int MAX_ITERATION_DEFAULT = 1000
const float MIN_RADIUS_LIMIT = 0.005
const float MAX_RADIUS_LIMIT = 0.500
const float EPS_ANGLE = 0.0f
const float MIN_OPENING_ANGLE = 100.0f
const float MAX_OPENING_ANGLE = 180.0f
Function Documentation
int main (int argc, char ** argv)
Definition at line 113 of file sphereSegmentationServer.cpp.
References pcm::PCManager::RANSAC_SPHERE_FILTER_SERVICE_NAME, and ransacSphereDetaction().
bool ransacSphereDetaction (PrimitiveSegmentation::Request & req, PrimitiveSegmentation::Response & res)
Definition at line 26 of file sphereSegmentationServer.cpp.
References pcm::PCManager::cloudForRosMsg(), pcm::PCManager::coefficientToVectorMsg(), DISTANCE_THRESHOLD_DEFAULT, EPS_ANGLE, pcm::PCManager::inlierToVectorMsg(), MAX_ITERATION_DEFAULT, MAX_OPENING_ANGLE, MAX_RADIUS_LIMIT, MIN_OPENING_ANGLE, MIN_RADIUS_LIMIT, NORMAL_DISTANCE_WEIGHT_DEFAULT, pcm::PCManager::normForRosMsg(), and seg.
Referenced by main().
Variable Documentation
const float DISTANCE_THRESHOLD_DEFAULT = 0.007f
Definition at line 17 of file sphereSegmentationServer.cpp.
Referenced by ransacSphereDetaction().
const float EPS_ANGLE = 0.0f
Definition at line 21 of file sphereSegmentationServer.cpp.
Referenced by ransacSphereDetaction().
const int MAX_ITERATION_DEFAULT = 1000
Definition at line 18 of file sphereSegmentationServer.cpp.
Referenced by ransacSphereDetaction().
const float MAX_OPENING_ANGLE = 180.0f
Definition at line 23 of file sphereSegmentationServer.cpp.
Referenced by ransacSphereDetaction().
const float MAX_RADIUS_LIMIT = 0.500
Definition at line 20 of file sphereSegmentationServer.cpp.
Referenced by ransacSphereDetaction().
const float MIN_OPENING_ANGLE = 100.0f
Definition at line 22 of file sphereSegmentationServer.cpp.
Referenced by ransacSphereDetaction().
const float MIN_RADIUS_LIMIT = 0.005
Definition at line 19 of file sphereSegmentationServer.cpp.
Referenced by ransacSphereDetaction().
const float NORMAL_DISTANCE_WEIGHT_DEFAULT = 0.001f
Definition at line 16 of file sphereSegmentationServer.cpp.
Referenced by ransacSphereDetaction().